import React, { createContext, useContext, useState } from "react";

export type Language = "el" | "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  el: {
    // Navigation
    "nav.home": "Αρχική",
    "nav.about": "Ο Γιατρός",
    "nav.services": "Υπηρεσίες",
    "nav.allServices": "Όλες οι Υπηρεσίες",
    "nav.contact": "Επικοινωνία",

    // Hero
    "hero.title": "Εξειδικευμένη Φροντίδα στη Γυναικολογία",
    "hero.subtitle": "Προσφέροντας εξατομικευμένη ιατρική φροντίδα με συμπόνια και επαγγελματισμό",
    "hero.cta": "Επικοινωνήστε",

    // About
    "about.seo.title": "Σχετικά με τον Δρ. Ελευθέριο Χειράκη - Γυναικολόγος & Ειδικός Υποβοηθούμενης Αναπαραγωγής",
    "about.seo.description": "Γνωρίστε τον Δρ. Ελευθέριο Χειράκη, ειδικό σε μαιευτική, γυναικολογία και υποβοηθούμενη αναπαραγωγή με διεθνή εμπειρία στην Ελλάδα και στο Παρίσι.",
    "about.hero.name": "Δρ. Ελευθέριος Χειράκης",
    "about.hero.title": "Μαιευτήρας - Γυναικολόγος - Ειδικός Υποβοηθούμενης Αναπαραγωγής",
    "about.subtitle": "Ειδικός στη γυναικεία αναπαραγωγική υγεία με διεθνή εκπαίδευση και εμπειρία",
    "about.hero.specialty": "Ειδικότητα: Μαιευτική, Γυναικολογία & Υποβοηθούμενη Αναπαραγωγή",
    "about.hero.experience": "15+ χρόνια εμπειρίας",
    "about.hero.description": "Με εξειδίκευση στη θεραπεία της υπογονιμότητας, την ενδοσκοπική χειρουργική και τη διαχείριση εγκυμοσύνης υψηλού κινδύνου, προσφέρω ολοκληρωμένη φροντίδα με βάση τις πιο σύγχρονες διεθνείς πρακτικές. Η εμπειρία μου σε κορυφαία κέντρα της Ελλάδας και του Παρισιού με έχει εξοπλίσει με τις γνώσεις και τις δεξιότητες για να παρέχω εξατομικευμένη, αποτελεσματική και συμπονετική ιατρική φροντίδα.",
    "about.education.title": "Εκπαίδευση & Εξειδίκευση",
    "about.education.intro": "Η ιατρική μου εκπαίδευση συνδυάζει ακαδημαϊκή αριστεία με διεθνή κλινική εμπειρία. Έχω εκπαιδευτεί σε κορυφαία ιδρύματα της Ευρώπης, αποκτώντας εξειδικευμένες γνώσεις στη μαιευτική, τη γυναικολογία και την υποβοηθούμενη αναπαραγωγή.",
    "about.education.medical.title": "Πτυχίο Ιατρικής",
    "about.education.medical.description": "Πτυχιούχος της Ιατρικής Σχολής του Πανεπιστημίου Ιατρικής και Φαρμακευτικής 'Grigore T. Popa' του Ιασίου, Ρουμανία, όπου απέκτησα στέρεα θεμελίωση στην κλινική ιατρική και τις ιατρικές επιστήμες.",
    "about.education.msc.title": "Μεταπτυχιακό στην Υποβοηθούμενη Αναπαραγωγή",
    "about.education.msc.description": "Master 2 στην Υποβοηθούμενη Αναπαραγωγή από το Πανεπιστήμιο Paris Descartes - Port Royal, Παρίσι. Αυτό το εξειδικευμένο πρόγραμμα μου παρείχε εμβάθυνση στις τεχνικές IVF, τη διαχείριση της υπογονιμότητας και τις πιο προηγμένες μεθόδους αναπαραγωγικής ιατρικής.",
    "about.education.endoscopy.title": "Πιστοποίηση Ενδοσκόπησης",
    "about.education.endoscopy.description": "Απόκτηση πτυχίων Bachelor Επιπέδου 1 και Επιπέδου 2 στην Ενδοσκόπηση από το Collège International de Chirurgie Endoscopique (CICE), Clermont-Ferrand, Γαλλία. Εξειδίκευση σε λαπαροσκοπικές και υστεροσκοπικές επεμβάσεις για τη θεραπεία γυναικολογικών παθήσεων με ελάχιστα επεμβατικές τεχνικές.",
    "about.education.laser.title": "Πιστοποίηση Laser Κόλπου",
    "about.education.laser.description": "Ολοκλήρωση εξειδικευμένης εκπαίδευσης στις θεραπείες laser κόλπου, συμπεριλαμβανομένων των συστημάτων Fotona και MonaLisa Touch, για τη θεραπεία κολπικής χαλάρωσης, ατροφίας και άλλων γυναικολογικών καταστάσεων.",
    "about.education.conferences.title": "Συνεχιζόμενη Ιατρική Εκπαίδευση",
    "about.education.conferences.description": "Τακτική συμμετοχή σε διεθνή ιατρικά συνέδρια και εργαστήρια, συμπεριλαμβανομένων του Ευρωπαϊκού Συνεδρίου Αναπαραγωγής και Εμβρυολογίας (ESHRE), του Παγκόσμιου Συνεδρίου Ενδομητρίωσης, και εξειδικευμένων σεμιναρίων σε ρομποτική χειρουργική και προηγμένες τεχνικές υποβοηθούμενης αναπαραγωγής.",
    "about.experience.title": "Επαγγελματική Εμπειρία",
    "about.experience.intro": "Η κλινική μου πρακτική εκτείνεται σε κορυφαία ιδρύματα της Ελλάδας και της Γαλλίας, όπου έχω αναπτύξει εμπειρία στη διαχείριση πολύπλοκων περιπτώσεων υπογονιμότητας, υψηλού κινδύνου εγκυμοσύνης και προηγμένων χειρουργικών επεμβάσεων.",
    "about.experience.current.title": "Τρέχουσες Θέσεις",
    "about.experience.current.embryoland.role": "Ειδικός Υποβοηθούμενης Αναπαραγωγής",
    "about.experience.current.embryoland.location": "Embryoland - Κέντρο Υποβοηθούμενης Αναπαραγωγής, Αθήνα",
    "about.experience.current.embryoland.description": "Παροχή ολοκληρωμένων υπηρεσιών εξωσωματικής γονιμοποίησης και θεραπείας υπογονιμότητας. Διενέργεια προηγμένων διαδικασιών IVF, ICSI, και Mini IVF με εξατομικευμένα πρωτόκολλα για τη μεγιστοποίηση των ποσοστών επιτυχίας.",
    "about.experience.current.rea.role": "Μαιευτήρας-Γυναικολόγος",
    "about.experience.current.rea.location": "REA Μαιευτική & Γυναικολογική Κλινική, Αθήνα",
    "about.experience.current.rea.description": "Διαχείριση μαιευτικών περιπτώσεων, συμπεριλαμβανομένων εγκυμοσυνών υψηλού κινδύνου, προγεννητικής διάγνωσης και τοκετών. Εξειδίκευση στη φροντίδα εγκύων με πολύπλοκες ιατρικές καταστάσεις.",
    "about.experience.current.tzaneio.role": "Μαιευτήρας-Γυναικολόγος",
    "about.experience.current.tzaneio.location": "Γενικό Νοσοκομείο Πειραιά 'Τζάνειο', Πειραιάς",
    "about.experience.current.tzaneio.description": "Παροχή γυναικολογικής και μαιευτικής φροντίδας σε δημόσιο νοσοκομείο, διαχείριση ποικίλων περιπτώσεων από ρουτίνα έως επείγουσες καταστάσεις. Συμμετοχή σε ακαδημαϊκή διδασκαλία και κλινική έρευνα.",
    "about.experience.current.diamantis.role": "Μαιευτήρας-Γυναικολόγος & Ειδικός Ενδοσκοπικής Χειρουργικής",
    "about.experience.current.diamantis.location": "Διαμάντης Clinic, Μαρούσι",
    "about.experience.current.diamantis.description": "Διενέργεια προηγμένων λαπαροσκοπικών και υστεροσκοπικών επεμβάσεων για τη θεραπεία ενδομητρίωσης, μυώματος, ωοθηκικών κύστεων και άλλων γυναικολογικών παθήσεων με ελάχιστα επεμβατικές τεχνικές.",
    "about.experience.current.euromedica.role": "Μαιευτήρας-Γυναικολόγος",
    "about.experience.current.euromedica.location": "EuroMedica - Αρωγή, Θεσσαλονίκη",
    "about.experience.current.euromedica.description": "Παροχή ολοκληρωμένων γυναικολογικών και μαιευτικών υπηρεσιών, συμπεριλαμβανομένης της προληπτικής φροντίδας, διαχείρισης εγκυμοσύνης και χειρουργικών επεμβάσεων.",
    "about.experience.international.title": "Διεθνής Εμπειρία",
    "about.experience.international.santulli.role": "Clinical Fellow - Ενδομητρίωση & Ρομποτική Χειρουργική",
    "about.experience.international.santulli.location": "Service du Pr Pietro Santulli, Hôpital Cochin, Παρίσι, Γαλλία",
    "about.experience.international.santulli.description": "Εξειδικευμένη εκπαίδευση στη θεραπεία της βαθιάς ενδομητρίωσης και στη ρομποτική γυναικολογική χειρουργική. Συμμετοχή σε πολύπλοκες επεμβάσεις για εξαίρεση ενδομητρίωσης, μυωμεκτομές και ανασυνδέσεις σαλπίγγων χρησιμοποιώντας το χειρουργικό σύστημα Da Vinci.",
    "about.experience.international.port_royal.role": "Fellow σε Υποβοηθούμενη Αναπαραγωγή",
    "about.experience.international.port_royal.location": "Maternité Port-Royal, Παρίσι, Γαλλία",
    "about.experience.international.port_royal.description": "Εξειδικευμένη εκπαίδευση σε προηγμένες τεχνικές IVF, διαχείριση δύσκολων περιπτώσεων υπογονιμότητας και έρευνα στην αναπαραγωγική ενδοκρινολογία σε ένα από τα κορυφαία κέντρα αναπαραγωγής στην Ευρώπη.",
    "about.experience.international.saint_joseph.role": "Resident στη Μαιευτική & Γυναικολογία",
    "about.experience.international.saint_joseph.location": "Hôpital Saint-Joseph, Παρίσι, Γαλλία",
    "about.experience.international.saint_joseph.description": "Ολοκληρωμένη εκπαίδευση σε μαιευτική, γυναικολογία και χειρουργική, συμπεριλαμβανομένης της διαχείρισης εγκυμοσυνών υψηλού κινδύνου, επειγόντων μαιευτικών καταστάσεων και γυναικολογικών επεμβάσεων.",
    "about.experience.international.tenon.role": "Resident στη Μαιευτική & Γυναικολογία",
    "about.experience.international.tenon.location": "Hôpital Tenon, Παρίσι, Γαλλία",
    "about.experience.international.tenon.description": "Κλινική εκπαίδευση σε ποικίλα γυναικολογικά και μαιευτικά θέματα, συμπεριλαμβανομένης της διαχείρισης τοκετών, προγεννητικής διάγνωσης και γυναικολογικής ογκολογίας.",
    "about.experience.international.other.description": "Πρόσθετη κλινική εμπειρία σε άλλα γαλλικά νοσοκομεία, συμπεριλαμβανομένων των Hôpital Beaujon, Hôpital Jean Verdier και Hôpital Jean Rostand, παρέχοντας ευρύ φάσμα έκθεσης σε διαφορετικές ιατρικές πρακτικές και πληθυσμούς ασθενών.",
    "about.experience.greece_other.title": "Προηγούμενη Εμπειρία στην Ελλάδα",
    "about.experience.greece_other.bladi.role": "Μαιευτήρας-Γυναικολόγος",
    "about.experience.greece_other.bladi.location": "Κλινική Αρ. Μπλαδή, Αθήνα",
    "about.experience.greece_other.bladi.description": "Παροχή γυναικολογικών και μαιευτικών υπηρεσιών, διενέργεια χειρουργικών επεμβάσεων και ανάπτυξη κλινικών δεξιοτήτων στη διαχείριση ποικίλων γυναικολογικών καταστάσεων.",
    "about.experience.greece_other.military.role": "Στρατιωτικός Ιατρός",
    "about.experience.greece_other.military.location": "414 SNEN, Ελληνική Πολεμική Αεροπορία",
    "about.experience.greece_other.military.description": "Παροχή ιατρικής φροντίδας σε στρατιωτικό περιβάλλον, διαχείριση επειγόντων περιστατικών και ανάπτυξη δεξιοτήτων υπό πίεση.",
    "about.expertise.title": "Ιατρική Εξειδίκευση",
    "about.expertise.intro": "Οι τομείς ιατρικής εξειδίκευσής μου καλύπτουν ένα ευρύ φάσμα γυναικολογικών και αναπαραγωγικών υπηρεσιών, με έμφαση στις πιο σύγχρονες και αποτελεσματικές θεραπείες.",
    "about.expertise.areas.endometriosis.title": "Ενδομητρίωση",
    "about.expertise.areas.endometriosis.description": "Εξειδικευμένη διάγνωση και θεραπεία της ενδομητρίωσης με προηγμένες λαπαροσκοπικές και ρομποτικές τεχνικές. Χειρουργική εξαίρεση βαθιάς ενδομητρίωσης, συμπεριλαμβανομένων περιπτώσεων με προσβολή εντέρου και ουροδόχου κύστης.",
    "about.expertise.areas.robotics.title": "Ρομποτική Χειρουργική",
    "about.expertise.areas.robotics.description": "Χρήση του ρομποτικού συστήματος Da Vinci για πολύπλοκες γυναικολογικές επεμβάσεις με μεγαλύτερη ακρίβεια, μικρότερο τραύμα και ταχύτερη ανάρρωση. Εξειδίκευση σε ρομποτικές μυωμεκτομές και υστερεκτομές.",
    "about.expertise.areas.ivf.title": "Εξωσωματική Γονιμοποίηση (IVF)",
    "about.expertise.areas.ivf.description": "Ολοκληρωμένες υπηρεσίες IVF με εξατομικευμένα πρωτόκολλα, συμπεριλαμβανομένου του κλασικού IVF, ICSI και Mini IVF. Χρήση των πιο σύγχρονων εργαστηριακών τεχνικών για μεγιστοποίηση των ποσοστών επιτυχίας.",
    "about.expertise.areas.infertility.title": "Διαχείριση Υπογονιμότητας",
    "about.expertise.areas.infertility.description": "Διερεύνηση και θεραπεία ανδρικής και γυναικείας υπογονιμότητας. Προσαρμοσμένα σχέδια θεραπείας που βασίζονται σε εμπεριστατωμένη διάγνωση και τις πιο πρόσφατες ιατρικές ενδείξεις.",
    "about.expertise.areas.cryopreservation.title": "Κρυοσυντήρηση Ωαρίων",
    "about.expertise.areas.cryopreservation.description": "Κρυοσυντήρηση ωαρίων για διατήρηση της γονιμότητας για ιατρικούς ή κοινωνικούς λόγους. Παροχή καθοδήγησης και υποστήριξης καθ' όλη τη διαδικασία.",
    "about.expertise.areas.obstetrics.title": "Μαιευτική Παρακολούθηση",
    "about.expertise.areas.obstetrics.description": "Ολοκληρωμένη προγεννητική και μαιευτική φροντίδα, συμπεριλαμβανομένης της διαχείρισης εγκυμοσυνών υψηλού κινδύνου, προγεννητικού ελέγχου και τοκετών. Υποστήριξη και καθοδήγηση καθ' όλη τη διάρκεια της εγκυμοσύνης.",
    "about.languages.title": "Γλώσσες",
    "about.languages.intro": "Η πολυγλωσσική μου ικανότητα μου επιτρέπει να επικοινωνώ αποτελεσματικά με ασθενείς από διαφορετικά πολιτιστικά και γλωσσικά υπόβαθρα.",
    "about.languages.greek": "Ελληνικά (Μητρική)",
    "about.languages.english": "Αγγλικά (C2)",
    "about.languages.french": "Γαλλικά (C1)",
    "about.languages.romanian": "Ρουμανικά (B2)",
    "about.philosophy.title": "Φιλοσοφία Φροντίδας",
    "about.philosophy.text": "Η προσέγγισή μου βασίζεται στην ολιστική και εξατομικευμένη φροντίδα κάθε γυναίκας. Πιστεύω στην ιατρική που βασίζεται σε επιστημονικά δεδομένα, συνδυασμένη με ανθρωπιά και κατανόηση των μοναδικών αναγκών κάθε ασθενούς. Η εμπειρία μου στη διεθνή ιατρική σκηνή, ιδιαίτερα στο Παρίσι, μου επέτρεψε να ενσωματώσω τις πιο σύγχρονες τεχνικές με μια προσέγγιση που θέτει την ασθενή στο κέντρο. Είτε πρόκειται για θέματα γονιμότητας, μαιευτικής παρακολούθησης ή χειρουργικών επεμβάσεων, στόχος μου είναι να προσφέρω την καλύτερη δυνατή φροντίδα με σεβασμό, εμπιστοσύνη και επαγγελματισμό.",

    // Services and other sections
    "services.title": "Υπηρεσίες",
    "services.obstetrics": "Μαιευτική",
    "services.gynecology": "Γυναικολογία",
    "services.assistedReproduction": "Υποβοηθούμενη Αναπαραγωγή",
    "services.endoscopy": "Ενδοσκοπική Χειρουργική",
    "services.laserTherapy": "Θεραπείες Laser",
    "services.consultation": "Ιατρικές Συμβουλές",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "The Doctor",
    "nav.services": "Services",
    "nav.allServices": "All Services",
    "nav.contact": "Contact",

    // Hero
    "hero.title": "Specialized Care in Gynecology",
    "hero.subtitle": "Providing personalized medical care with compassion and professionalism",
    "hero.cta": "Contact Us",

    // About
    "about.seo.title": "About Dr. Eleftherios Cheirakis - Gynecologist & Assisted Reproduction Specialist",
    "about.seo.description": "Meet Dr. Eleftherios Cheirakis, specialist in obstetrics, gynecology and assisted reproduction with international experience in Greece and Paris.",
    "about.hero.name": "Dr. Eleftherios Cheirakis",
    "about.hero.title": "Obstetrician - Gynecologist - Assisted Reproduction Specialist",
    "about.subtitle": "Specialist in women's reproductive health with international training and expertise",
    "about.hero.specialty": "Specialty: Obstetrics, Gynecology & Assisted Reproduction",
    "about.hero.experience": "15+ years of experience",
    "about.hero.description": "Specializing in infertility treatment, endoscopic surgery and high-risk pregnancy management, I provide comprehensive care based on the most current international practices. My experience in leading centers in Greece and Paris has equipped me with the knowledge and skills to provide personalized, effective and compassionate medical care.",
    "about.education.title": "Education & Specialization",
    "about.education.intro": "My medical education combines academic excellence with international clinical experience. I have trained at top European institutions, acquiring specialized knowledge in obstetrics, gynecology and assisted reproduction.",
    "about.education.medical.title": "Medical Degree",
    "about.education.medical.description": "Graduate of the Medical School of 'Grigore T. Popa' University of Medicine and Pharmacy, Iași, Romania, where I acquired a solid foundation in clinical medicine and medical sciences.",
    "about.education.msc.title": "Master's Degree in Assisted Reproduction",
    "about.education.msc.description": "Master 2 in Assisted Reproduction from Paris Descartes University - Port Royal, Paris. This specialized program provided me with in-depth knowledge of IVF techniques, infertility management and the most advanced reproductive medicine methods.",
    "about.education.endoscopy.title": "Endoscopy Certification",
    "about.education.endoscopy.description": "Bachelor Level 1 and Level 2 degrees in Endoscopy from the Collège International de Chirurgie Endoscopique (CICE), Clermont-Ferrand, France. Specialization in laparoscopic and hysteroscopic procedures for treating gynecological conditions with minimally invasive techniques.",
    "about.education.laser.title": "Vaginal Laser Certification",
    "about.education.laser.description": "Completion of specialized training in vaginal laser therapies, including Fotona and MonaLisa Touch systems, for treating vaginal laxity, atrophy and other gynecological conditions.",
    "about.education.conferences.title": "Continuing Medical Education",
    "about.education.conferences.description": "Regular participation in international medical conferences and workshops, including the European Society of Human Reproduction and Embryology (ESHRE) Congress, World Endometriosis Congress, and specialized seminars in robotic surgery and advanced assisted reproduction techniques.",
    "about.experience.title": "Professional Experience",
    "about.experience.intro": "My clinical practice spans leading institutions in Greece and France, where I have developed expertise in managing complex infertility cases, high-risk pregnancies and advanced surgical procedures.",
    "about.experience.current.title": "Current Positions",
    "about.experience.current.embryoland.role": "Assisted Reproduction Specialist",
    "about.experience.current.embryoland.location": "Embryoland - Assisted Reproduction Center, Athens",
    "about.experience.current.embryoland.description": "Providing comprehensive IVF services and infertility treatment. Performing advanced IVF, ICSI, and Mini IVF procedures with personalized protocols to maximize success rates.",
    "about.experience.current.rea.role": "Obstetrician-Gynecologist",
    "about.experience.current.rea.location": "REA Maternity & Gynecology Clinic, Athens",
    "about.experience.current.rea.description": "Managing obstetric cases, including high-risk pregnancies, prenatal diagnosis and deliveries. Specializing in the care of pregnant women with complex medical conditions.",
    "about.experience.current.tzaneio.role": "Obstetrician-Gynecologist",
    "about.experience.current.tzaneio.location": "General Hospital of Piraeus 'Tzaneio', Piraeus",
    "about.experience.current.tzaneio.description": "Providing gynecological and obstetric care in a public hospital setting, managing a variety of cases from routine to emergencies. Participating in academic teaching and clinical research.",
    "about.experience.current.diamantis.role": "Obstetrician-Gynecologist & Endoscopic Surgery Specialist",
    "about.experience.current.diamantis.location": "Diamantis Clinic, Marousi",
    "about.experience.current.diamantis.description": "Performing advanced laparoscopic and hysteroscopic procedures for treating endometriosis, fibroids, ovarian cysts and other gynecological conditions with minimally invasive techniques.",
    "about.experience.current.euromedica.role": "Obstetrician-Gynecologist",
    "about.experience.current.euromedica.location": "EuroMedica - Arogi, Thessaloniki",
    "about.experience.current.euromedica.description": "Providing comprehensive gynecological and obstetric services, including preventive care, pregnancy management and surgical procedures.",
    "about.experience.international.title": "International Experience",
    "about.experience.international.santulli.role": "Clinical Fellow - Endometriosis & Robotic Surgery",
    "about.experience.international.santulli.location": "Service of Pr Pietro Santulli, Hôpital Cochin, Paris, France",
    "about.experience.international.santulli.description": "Specialized training in deep endometriosis treatment and robotic gynecological surgery. Participation in complex procedures for endometriosis excision, myomectomies and tubal reanastomosis using the Da Vinci surgical system.",
    "about.experience.international.port_royal.role": "Fellow in Assisted Reproduction",
    "about.experience.international.port_royal.location": "Maternité Port-Royal, Paris, France",
    "about.experience.international.port_royal.description": "Specialized training in advanced IVF techniques, management of difficult infertility cases and research in reproductive endocrinology at one of Europe's leading reproduction centers.",
    "about.experience.international.saint_joseph.role": "Resident in Obstetrics & Gynecology",
    "about.experience.international.saint_joseph.location": "Hôpital Saint-Joseph, Paris, France",
    "about.experience.international.saint_joseph.description": "Comprehensive training in obstetrics, gynecology and surgery, including management of high-risk pregnancies, obstetric emergencies and gynecological procedures.",
    "about.experience.international.tenon.role": "Resident in Obstetrics & Gynecology",
    "about.experience.international.tenon.location": "Hôpital Tenon, Paris, France",
    "about.experience.international.tenon.description": "Clinical training in various gynecological and obstetric topics, including delivery management, prenatal diagnosis and gynecological oncology.",
    "about.experience.international.other.description": "Additional clinical experience in other French hospitals, including Hôpital Beaujon, Hôpital Jean Verdier and Hôpital Jean Rostand, providing broad exposure to different medical practices and patient populations.",
    "about.experience.greece_other.title": "Previous Experience in Greece",
    "about.experience.greece_other.bladi.role": "Obstetrician-Gynecologist",
    "about.experience.greece_other.bladi.location": "Ari. Bladi Clinic, Athens",
    "about.experience.greece_other.bladi.description": "Providing gynecological and obstetric services, performing surgical procedures and developing clinical skills in managing various gynecological conditions.",
    "about.experience.greece_other.military.role": "Military Physician",
    "about.experience.greece_other.military.location": "414 SNEN, Hellenic Air Force",
    "about.experience.greece_other.military.description": "Providing medical care in a military environment, managing emergency cases and developing skills under pressure.",
    "about.expertise.title": "Medical Expertise",
    "about.expertise.intro": "My areas of medical expertise cover a wide range of gynecological and reproductive services, with emphasis on the most modern and effective treatments.",
    "about.expertise.areas.endometriosis.title": "Endometriosis",
    "about.expertise.areas.endometriosis.description": "Specialized diagnosis and treatment of endometriosis with advanced laparoscopic and robotic techniques. Surgical excision of deep endometriosis, including cases with bowel and bladder involvement.",
    "about.expertise.areas.robotics.title": "Robotic Surgery",
    "about.expertise.areas.robotics.description": "Use of the Da Vinci robotic system for complex gynecological procedures with greater precision, less trauma and faster recovery. Specialization in robotic myomectomies and hysterectomies.",
    "about.expertise.areas.ivf.title": "In Vitro Fertilization (IVF)",
    "about.expertise.areas.ivf.description": "Comprehensive IVF services with personalized protocols, including classic IVF, ICSI and Mini IVF. Use of the most modern laboratory techniques to maximize success rates.",
    "about.expertise.areas.infertility.title": "Infertility Management",
    "about.expertise.areas.infertility.description": "Investigation and treatment of male and female infertility. Tailored treatment plans based on thorough diagnosis and the latest medical evidence.",
    "about.expertise.areas.cryopreservation.title": "Egg Cryopreservation",
    "about.expertise.areas.cryopreservation.description": "Egg cryopreservation for fertility preservation for medical or social reasons. Providing guidance and support throughout the process.",
    "about.expertise.areas.obstetrics.title": "Obstetric Care",
    "about.expertise.areas.obstetrics.description": "Comprehensive prenatal and obstetric care, including management of high-risk pregnancies, prenatal screening and deliveries. Support and guidance throughout pregnancy.",
    "about.languages.title": "Languages",
    "about.languages.intro": "My multilingual ability allows me to communicate effectively with patients from different cultural and linguistic backgrounds.",
    "about.languages.greek": "Greek (Native)",
    "about.languages.english": "English (C2)",
    "about.languages.french": "French (C1)",
    "about.languages.romanian": "Romanian (B2)",
    "about.philosophy.title": "Philosophy of Care",
    "about.philosophy.text": "My approach is based on holistic and personalized care for each woman. I believe in evidence-based medicine, combined with humanity and understanding of each patient's unique needs. My experience on the international medical scene, particularly in Paris, has allowed me to integrate the most modern techniques with an approach that puts the patient at the center. Whether it's fertility issues, obstetric monitoring or surgical procedures, my goal is to provide the best possible care with respect, trust and professionalism.",

    // Services and other sections
    "services.title": "Services",
    "services.obstetrics": "Obstetrics",
    "services.gynecology": "Gynecology",
    "services.assistedReproduction": "Assisted Reproduction",
    "services.endoscopy": "Endoscopic Surgery",
    "services.laserTherapy": "Laser Therapies",
    "services.consultation": "Medical Consultations",
  },
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.about": "Le Médecin",
    "nav.services": "Services",
    "nav.allServices": "Tous les Services",
    "nav.contact": "Contact",

    // Hero
    "hero.title": "Soins Spécialisés en Gynécologie",
    "hero.subtitle": "Offrir des soins médicaux personnalisés avec compassion et professionnalisme",
    "hero.cta": "Contactez-nous",

    // About
    "about.seo.title": "À propos du Dr Eleftherios Cheirakis - Gynécologue & Spécialiste en Procréation Assistée",
    "about.seo.description": "Rencontrez le Dr Eleftherios Cheirakis, spécialiste en obstétrique, gynécologie et procréation assistée avec une expérience internationale en Grèce et à Paris.",
    "about.hero.name": "Dr. Eleftherios Cheirakis",
    "about.hero.title": "Obstétricien - Gynécologue - Spécialiste en Procréation Assistée",
    "about.subtitle": "Spécialiste en santé reproductive féminine avec formation et expertise internationales",
    "about.hero.specialty": "Spécialité : Obstétrique, Gynécologie et Procréation Assistée",
    "about.hero.experience": "Plus de 15 ans d'expérience",
    "about.hero.description": "Spécialisé dans le traitement de l'infertilité, la chirurgie endoscopique et la gestion des grossesses à haut risque, je fournis des soins complets basés sur les pratiques internationales les plus récentes. Mon expérience dans des centres de premier plan en Grèce et à Paris m'a doté des connaissances et des compétences nécessaires pour fournir des soins médicaux personnalisés, efficaces et compatissants.",
    "about.education.title": "Formation & Spécialisation",
    "about.education.intro": "Ma formation médicale combine l'excellence académique avec une expérience clinique internationale. J'ai été formé dans les meilleures institutions européennes, acquérant des connaissances spécialisées en obstétrique, gynécologie et procréation assistée.",
    "about.education.medical.title": "Diplôme de Médecine",
    "about.education.medical.description": "Diplômé de la Faculté de Médecine de l'Université de Médecine et de Pharmacie 'Grigore T. Popa' d'Iași, Roumanie, où j'ai acquis une base solide en médecine clinique et en sciences médicales.",
    "about.education.msc.title": "Master en Procréation Assistée",
    "about.education.msc.description": "Master 2 en Procréation Assistée de l'Université Paris Descartes - Port Royal, Paris. Ce programme spécialisé m'a fourni une connaissance approfondie des techniques de FIV, de la gestion de l'infertilité et des méthodes les plus avancées de médecine reproductive.",
    "about.education.endoscopy.title": "Certification en Endoscopie",
    "about.education.endoscopy.description": "Diplômes de Bachelor Niveau 1 et Niveau 2 en Endoscopie du Collège International de Chirurgie Endoscopique (CICE), Clermont-Ferrand, France. Spécialisation dans les procédures laparoscopiques et hystéroscopiques pour traiter les pathologies gynécologiques avec des techniques minimalement invasives.",
    "about.education.laser.title": "Certification Laser Vaginal",
    "about.education.laser.description": "Achèvement d'une formation spécialisée dans les thérapies laser vaginales, y compris les systèmes Fotona et MonaLisa Touch, pour traiter le relâchement vaginal, l'atrophie et d'autres conditions gynécologiques.",
    "about.education.conferences.title": "Formation Médicale Continue",
    "about.education.conferences.description": "Participation régulière à des congrès et ateliers médicaux internationaux, notamment le Congrès de la Société Européenne de Reproduction Humaine et d'Embryologie (ESHRE), le Congrès Mondial sur l'Endométriose, et des séminaires spécialisés en chirurgie robotique et techniques avancées de procréation assistée.",
    "about.experience.title": "Expérience Professionnelle",
    "about.experience.intro": "Ma pratique clinique s'étend à des institutions de premier plan en Grèce et en France, où j'ai développé une expertise dans la gestion de cas complexes d'infertilité, de grossesses à haut risque et de procédures chirurgicales avancées.",
    "about.experience.current.title": "Postes Actuels",
    "about.experience.current.embryoland.role": "Spécialiste en Procréation Assistée",
    "about.experience.current.embryoland.location": "Embryoland - Centre de Procréation Assistée, Athènes",
    "about.experience.current.embryoland.description": "Fournir des services complets de FIV et de traitement de l'infertilité. Réaliser des procédures avancées de FIV, ICSI et Mini FIV avec des protocoles personnalisés pour maximiser les taux de réussite.",
    "about.experience.current.rea.role": "Obstétricien-Gynécologue",
    "about.experience.current.rea.location": "Clinique de Maternité et de Gynécologie REA, Athènes",
    "about.experience.current.rea.description": "Gestion de cas obstétricaux, y compris les grossesses à haut risque, le diagnostic prénatal et les accouchements. Spécialisation dans les soins aux femmes enceintes présentant des conditions médicales complexes.",
    "about.experience.current.tzaneio.role": "Obstétricien-Gynécologue",
    "about.experience.current.tzaneio.location": "Hôpital Général du Pirée 'Tzaneio', Le Pirée",
    "about.experience.current.tzaneio.description": "Fournir des soins gynécologiques et obstétricaux dans un hôpital public, gérant une variété de cas allant de la routine aux urgences. Participation à l'enseignement académique et à la recherche clinique.",
    "about.experience.current.diamantis.role": "Obstétricien-Gynécologue & Spécialiste en Chirurgie Endoscopique",
    "about.experience.current.diamantis.location": "Clinique Diamantis, Marousi",
    "about.experience.current.diamantis.description": "Réaliser des procédures laparoscopiques et hystéroscopiques avancées pour traiter l'endométriose, les fibromes, les kystes ovariens et d'autres pathologies gynécologiques avec des techniques minimalement invasives.",
    "about.experience.current.euromedica.role": "Obstétricien-Gynécologue",
    "about.experience.current.euromedica.location": "EuroMedica - Arogi, Thessalonique",
    "about.experience.current.euromedica.description": "Fournir des services gynécologiques et obstétricaux complets, y compris les soins préventifs, la gestion de la grossesse et les procédures chirurgicales.",
    "about.experience.international.title": "Expérience Internationale",
    "about.experience.international.santulli.role": "Clinical Fellow - Endométriose & Chirurgie Robotique",
    "about.experience.international.santulli.location": "Service du Pr Pietro Santulli, Hôpital Cochin, Paris, France",
    "about.experience.international.santulli.description": "Formation spécialisée dans le traitement de l'endométriose profonde et la chirurgie gynécologique robotique. Participation à des procédures complexes d'excision d'endométriose, myomectomies et réanastomoses tubaires utilisant le système chirurgical Da Vinci.",
    "about.experience.international.port_royal.role": "Fellow en Procréation Assistée",
    "about.experience.international.port_royal.location": "Maternité Port-Royal, Paris, France",
    "about.experience.international.port_royal.description": "Formation spécialisée en techniques avancées de FIV, gestion de cas difficiles d'infertilité et recherche en endocrinologie de la reproduction dans l'un des centres de reproduction les plus importants d'Europe.",
    "about.experience.international.saint_joseph.role": "Résident en Obstétrique & Gynécologie",
    "about.experience.international.saint_joseph.location": "Hôpital Saint-Joseph, Paris, France",
    "about.experience.international.saint_joseph.description": "Formation complète en obstétrique, gynécologie et chirurgie, y compris la gestion des grossesses à haut risque, les urgences obstétricales et les procédures gynécologiques.",
    "about.experience.international.tenon.role": "Résident en Obstétrique & Gynécologie",
    "about.experience.international.tenon.location": "Hôpital Tenon, Paris, France",
    "about.experience.international.tenon.description": "Formation clinique sur divers sujets gynécologiques et obstétricaux, y compris la gestion des accouchements, le diagnostic prénatal et l'oncologie gynécologique.",
    "about.experience.international.other.description": "Expérience clinique supplémentaire dans d'autres hôpitaux français, notamment l'Hôpital Beaujon, l'Hôpital Jean Verdier et l'Hôpital Jean Rostand, offrant une large exposition à différentes pratiques médicales et populations de patients.",
    "about.experience.greece_other.title": "Expérience Antérieure en Grèce",
    "about.experience.greece_other.bladi.role": "Obstétricien-Gynécologue",
    "about.experience.greece_other.bladi.location": "Clinique Ari. Bladi, Athènes",
    "about.experience.greece_other.bladi.description": "Fournir des services gynécologiques et obstétricaux, réaliser des procédures chirurgicales et développer des compétences cliniques dans la gestion de diverses conditions gynécologiques.",
    "about.experience.greece_other.military.role": "Médecin Militaire",
    "about.experience.greece_other.military.location": "414 SNEN, Force Aérienne Hellénique",
    "about.experience.greece_other.military.description": "Fournir des soins médicaux dans un environnement militaire, gérer des cas d'urgence et développer des compétences sous pression.",
    "about.expertise.title": "Expertise Médicale",
    "about.expertise.intro": "Mes domaines d'expertise médicale couvrent un large éventail de services gynécologiques et reproductifs, en mettant l'accent sur les traitements les plus modernes et efficaces.",
    "about.expertise.areas.endometriosis.title": "Endométriose",
    "about.expertise.areas.endometriosis.description": "Diagnostic et traitement spécialisés de l'endométriose avec des techniques laparoscopiques et robotiques avancées. Excision chirurgicale de l'endométriose profonde, y compris les cas avec atteinte intestinale et vésicale.",
    "about.expertise.areas.robotics.title": "Chirurgie Robotique",
    "about.expertise.areas.robotics.description": "Utilisation du système robotique Da Vinci pour des procédures gynécologiques complexes avec une plus grande précision, moins de traumatismes et une récupération plus rapide. Spécialisation dans les myomectomies et hystérectomies robotiques.",
    "about.expertise.areas.ivf.title": "Fécondation In Vitro (FIV)",
    "about.expertise.areas.ivf.description": "Services complets de FIV avec des protocoles personnalisés, y compris la FIV classique, l'ICSI et la Mini FIV. Utilisation des techniques de laboratoire les plus modernes pour maximiser les taux de réussite.",
    "about.expertise.areas.infertility.title": "Gestion de l'Infertilité",
    "about.expertise.areas.infertility.description": "Investigation et traitement de l'infertilité masculine et féminine. Plans de traitement personnalisés basés sur un diagnostic approfondi et les dernières preuves médicales.",
    "about.expertise.areas.cryopreservation.title": "Cryoconservation Ovocytaire",
    "about.expertise.areas.cryopreservation.description": "Cryoconservation des ovocytes pour la préservation de la fertilité pour des raisons médicales ou sociales. Fourniture de conseils et de soutien tout au long du processus.",
    "about.expertise.areas.obstetrics.title": "Suivi Obstétrical",
    "about.expertise.areas.obstetrics.description": "Soins prénatals et obstétricaux complets, y compris la gestion des grossesses à haut risque, le dépistage prénatal et les accouchements. Soutien et guidance tout au long de la grossesse.",
    "about.languages.title": "Langues",
    "about.languages.intro": "Ma capacité multilingue me permet de communiquer efficacement avec des patients de différents horizons culturels et linguistiques.",
    "about.languages.greek": "Grec (Langue maternelle)",
    "about.languages.english": "Anglais (C2)",
    "about.languages.french": "Français (C1)",
    "about.languages.romanian": "Roumain (B2)",
    "about.philosophy.title": "Philosophie de Soins",
    "about.philosophy.text": "Mon approche est basée sur des soins holistiques et personnalisés pour chaque femme. Je crois en une médecine fondée sur des preuves scientifiques, combinée avec humanité et compréhension des besoins uniques de chaque patiente. Mon expérience sur la scène médicale internationale, particulièrement à Paris, m'a permis d'intégrer les techniques les plus modernes avec une approche centrée sur la patiente. Qu'il s'agisse de questions de fertilité, de suivi obstétrical ou de procédures chirurgicales, mon objectif est de fournir les meilleurs soins possibles avec respect, confiance et professionnalisme.",

    // Services and other sections
    "services.title": "Services",
    "services.obstetrics": "Obstétrique",
    "services.gynecology": "Gynécologie",
    "services.assistedReproduction": "Procréation Assistée",
    "services.endoscopy": "Chirurgie Endoscopique",
    "services.laserTherapy": "Thérapies Laser",
    "services.consultation": "Consultations Médicales",
  },
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>("el");

  const t = (key: string): string => {
    const value = translations[language][key];
    if (!value) {
      console.warn(`Translation missing for key: ${key} in language: ${language}`);
      return key;
    }
    return value;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
